### ISSUE TITLE
FLTK version pset command draws an extra pixel

### ISSUE THREAD

**Issue by leonardtsai** [smallbasic/smallbasic.github.io#1]
FLTK  version pset command draws an extra pixel.
To fix that, modify fltk/display.cxx as below.

void Canvas::drawPixel(int posX, int posY) {
  ~~~~
  //fl_line(posX, posY, posX+1, posY+1);
  fl_point(posX, posY);
  ~~~~
}

**Comment by chrisws** [comment]
Fixed, thanks for reporting the issue !
