### ISSUE TITLE
Dimension swapped when creating image from 2d array

### ISSUE THREAD

**Issue by leonardtsai** [smallbasic/smallbasic.github.io#2]
Tested on 12.20 FLTK version.

Document tells me the first dimension is y and 2nd dimension is x. But I follow that instruction, ex. dim a(479, 639), the result is wrong. dim a(639, 479) will be correct, but when setting pixel, you have to put y dimension in the first position, i.e. a(479, 639) is the right bottom pixel.

After looking into src/ui/image.cpp, I guess the problem located at ImageBuffer *load_image(var_t *var).

line 178,

} else if (var->type == V_ARRAY && v_maxdim(var) == 2) {
  int w = ABS(v_lbount(var, 0) - v_ubound(var, 0)) + 1 // 1st dimension is used as width
  int h = ABS(v_lbount(var, 1) - v_ubound(var, 1)) + 1 // 2nd dimension is used as height

**Comment by chrisws** [comment]
Thanks for your report.

I've already made some changes to address these issues. Could you please take a look here https://github.com/chrisws/SmallBASIC/tree/12_22 and let me know if you spot any more problems?

**Comment by leonardtsai** [comment]
It's weird. I use this simple program and I didn't see any red pixel. Normally, I expect two red pixel at upper left and upper right.

option predef grmode 1024x768
cls
dim imgArr(768-1,1024-1)
imgArr(0,0) = rgb(255,0,0)
imgArr(0,1023) = rgb(255,0,0)
im = image(imgArr)
im.show(0, 0)
pause   

Leonard

**Comment by chrisws** [comment]
If you are working from the 12_22 branch there's some more changes. The format of IMAGE data is now 32 bits ARGB, so you can't use the built-in rgb() function. Here's the required changes:
```
option predef grmode 1024x768
def argb(r, g, b) = (255 lshift 24) + (r lshift 16) + (g lshift 8) + b
cls
dim imgArr(768-1,1024-1)
imgArr(0,0) = argb(255,0,0)
imgArr(0,1023) = argb(255,0,0)
im = image(imgArr)
im.show(0, 0)
```
[edit] - Just realised I can support both formats so your code example will still work (after git pull)

**Comment by chrisws** [comment]
Fixed, thanks for reporting the issue !
