### ISSUE TITLE
Feature Request: cursor row and column position.

### ISSUE THREAD

**Issue by redwdc** [smallbasic/smallbasic.github.io#5]
QBasic 4.5 (and QB64) have 2 built in functions to save the cursor position.

CSRLIN for the row: `row = CSRLIN`

POS for the column: `column = POS`

For a better/more in-depth explanation see: [https://wiki.qb64.org/wiki/CSRLIN](url)

redwdc

**Comment by chrisws** [comment]
Hi redwdc,

Thanks for the suggestion. These functions can be easily "polyfilled" like this:

```
def CSRLIN = ypos
def pos(x) = xpos

LOCATE 5, 5: PRINT "HELLO ";
Y = CSRLIN 'save the row
X = POS(0) 'save the column  
LOCATE 10, 10: PRINT "WORLD"
LOCATE Y, X 'restore saved position
PRINT "GOODBYE" 
```

So there's no need to implement these as core functions.
